apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config-users
data:
  PAYMENT_INTEGRATION_HOST: "https://api.mercadopago.com/"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
data: {}
type: Opaque
